// Vue_version/tickety/src/components/pages/Login.vue
<template>
  <div>
    <AuthForm type="Login" :onSubmit="handleLogin" />
    <p class="text-center mt-4 text-gray-600">
      Don’t have an account?
      <RouterLink to="/auth/signup" class="text-blue-600 hover:underline"
        >Sign up</RouterLink
      >
    </p>
  </div>
</template>

<script setup>
import { useRouter } from "vue-router";
import AuthForm from "../AuthForm.vue";

const router = useRouter();

function handleLogin({ email, password }) {
  const storedUser = JSON.parse(localStorage.getItem("ticketapp_user"));
  if (
    !storedUser ||
    storedUser.email !== email ||
    storedUser.password !== password
  ) {
    alert("Invalid credentials. Please try again.");
    return;
  }
  localStorage.setItem("ticketapp_session", "mock-session-token");
  router.push("/dashboard");
}
</script>

// React_Version/tickety/src/components/pages/Login.jsx
import { useNavigate, Link } from "react-router-dom";
import AuthForm from "../AuthForm";

function Login() {
  const navigate = useNavigate();

  // Handles login submission
  const handleLogin = ({ email, password }) => {
    const storedUser = JSON.parse(localStorage.getItem("ticketapp_user"));

    // Check if user exists and password matches
    if (
      !storedUser ||
      storedUser.email !== email ||
      storedUser.password !== password
    ) {
      alert("Invalid credentials. Please try again.");
      return;
    }

    // Save fake session token
    localStorage.setItem("ticketapp_session", "mock-session-token");

    // Redirect to dashboard
    navigate("/dashboard");
  };

  return (
    <div>
      <AuthForm type="login" onSubmit={handleLogin} />

      <p className="text-center mt-4 text-gray-600">
        Don’t have an account?{" "}
        <Link to="/auth/signup" className="text-blue-600 hover:underline">
          Sign up
        </Link>
      </p>
    </div>
  );
}

export default Login;
